#!/usr/bin/env bash

# GIT FUNCTIONS
git_branch() {
    git branch 2>/dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
# TERMINAL PROMPT
# PS1="\[\e[0;93m\]\u\[\e[m\]"    # username
# PS1+=" "    # space
# PS1+="\[\e[0;95m\]\W\[\e[m\]"    # current directory
# PS1+="\[\e[0;92m\]\$(git_branch)\[\e[m\]"    # current branch
# PS1+=" "    # space
# PS1+=" $ "    # end prompt
PS1="`a=$?;if [ $a -ne 0 ]; then a="  "$a; echo -ne "\[\e[1A\e[$((COLUMNS-2))G\e[31m\e[1;41m${a:(-3)}\]\[\e[0m\e[7m\e[2m\r\n\]";fi`${debian_chroot:+($debian_chroot)}\[\e[1;33m\]\u\[\e[1;31m\]@\[\e[1;35m\]\h\[\e[1;32m\][\t]\[\e[1;31m\]\[\e[0;92m\]\$(git_branch)\[\e[m\]:\[\e[1;36m\]\w\[\e[1;34m\]\$\[\e[0;39m\] "

export PS1;
export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
